services:
  - type: web
    name: school-system-backend
    runtime: node
    plan: free
    # Run project build (installs dev deps, compiles server, builds client)
    buildCommand: npm run build
    # Start the compiled Node server
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        scope: runtime
        # You'll set this in Render dashboard
      - key: PORT
        value: 5004
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
    autoDeploy: true
    branch: main
